version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: shard
    restart: unless-stopped
    tty: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pw@2024
      POSTGRES_DB: sharding
    ports:
      - "7001:5432"  # Expose PostgreSQL port
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
